/*회원정보*/
CREATE TABLE USERS (
    UNO INT UNSIGNED AUTO_INCREMENT,
    USERID VARCHAR(10) NOT NULL,
    USERPW VARCHAR(100) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    GENDER CHAR(1) DEFAULT 'M' NOT NULL,
    BIRTH DATE NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(20) NOT NULL,
    ZONECODE VARCHAR(10),
    ADDRESS VARCHAR(100),
    ADDRESSDETAIL VARCHAR(100),
    REGDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ENABLED CHAR(1) DEFAULT '1',
    PRIMARY KEY (USERID),
    UNIQUE KEY UK_USERS (UNO)
);

/*기본입력 - 관리자계정 등록*/
insert into users (userid, userpw, name, phone, email, address, birth, regdate, updatedate, enabled, gender, zonecode, addressdetail) 
values ('admin', '1234', '관리자', '', 'kevinyh18@gmail.com', '', '', current_timestamp, current_timestamp, 1, 'M', '', '');
/*기본입력 - 관리자계정 권한 부여*/
INSERT INTO AUTH (USERID, AUTH) VALUES ('admin', 'ROLE_ADMIN');
/*기본입력 - 관리자계정 권한 프로필사진등록_추후 클라이언트는 수정만 가능*/
INSERT INTO PROFILE (UUID, UPLOADPATH, FILENAME, FILETYPE, USERID) VALUES ('ed87212c-4e79-4813-be6c-8c73ac58ac33','profile','Default-Profile.png',1,'admin');
/*기본입력 - 메인화면 글등록_추후 클라이언트는 수정만 가능*/
INSERT INTO INTRO (TITLE_TITLE, BOARDTYPE) values ('메인화면 제목입니다.', 1);
/*기본입력 - 소개화면 글등록_추후 클라이언트는 수정만 가능*/
INSERT INTO INTRO (TITLE_TITLE, BOARDTYPE) values ('소개화면 제목입니다.', 2);

/*회원권한*/
CREATE TABLE AUTH (
    USERID VARCHAR(10) NOT NULL,
    AUTH VARCHAR(15) DEFAULT 'ROLE_USER' NOT NULL,
    PRIMARY KEY (USERID),
    CONSTRAINT FK_USERS_AUTH FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);

/*로그인기록*/
CREATE TABLE PERSISTENT_LOGINS (
    USERNAME VARCHAR(64) NOT NULL,
    SERIES VARCHAR(64),
    TOKEN VARCHAR(64) NOT NULL,
    LAST_USED TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (SERIES)
);

/*프로필사진*/
CREATE TABLE PROFILE (
    USERID VARCHAR(10) NOT NULL,
    UUID VARCHAR(100) NOT NULL,
    UPLOADPATH VARCHAR(200) NOT NULL,
    FILENAME VARCHAR(100) NOT NULL,
    FILETYPE CHAR(1) DEFAULT 'I',
    PRIMARY KEY (USERID),
    CONSTRAINT FK_PROFILE_USERS FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);

/*본인인증메일-난수저장*/
CREATE TABLE CHECKMAIL (
    EMAIL VARCHAR(20) NOT NULL,
    CHECKSTR VARCHAR(10) NOT NULL,
    PRIMARY KEY (EMAIL)
);

/*일반게시판*/
CREATE TABLE BOARD (
    BNO INT UNSIGNED AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT NOT NULL,
    WRITER VARCHAR(10) NOT NULL,
    REGDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    REPLYCNT INT DEFAULT 0,
    HIT INT UNSIGNED DEFAULT 0,
    BOARDTYPE VARCHAR(10) DEFAULT '1',    
    PRIMARY KEY (BNO),
    CONSTRAINT FK_USER_BOARD FOREIGN KEY (WRITER) REFERENCES USERS(USERID) ON DELETE CASCADE
);

/*일반게시판-첨부파일*/
CREATE TABLE BOARD_ATTACH (
    BNO INT UNSIGNED,
    UUID VARCHAR(100) NOT NULL,
    UPLOADPATH VARCHAR(200) NOT NULL,
    FILENAME VARCHAR(100) NOT NULL,
    FILETYPE CHAR(1) DEFAULT 'I',    
    PRIMARY KEY (UUID),
    CONSTRAINT FK_BOARD_ATTACH FOREIGN KEY (BNO) REFERENCES BOARD(BNO) ON DELETE CASCADE
);

/*일반게시판-댓글*/
CREATE TABLE BOARD_REPLY (    
    RNO INT UNSIGNED AUTO_INCREMENT,    
    REPLY TEXT NOT NULL,
    REPLYER VARCHAR(10) NOT NULL,
    REPLYDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    BNO INT UNSIGNED NOT NULL,
    BOARDTYPE VARCHAR(10) DEFAULT '1.1',    
    PRIMARY KEY (RNO),
    CONSTRAINT FK_BOARD_REPLY FOREIGN KEY (BNO) REFERENCES BOARD(BNO) ON DELETE CASCADE,
    CONSTRAINT FK_USER_BOARD_REPLY FOREIGN KEY (REPLYER) REFERENCES USERS(USERID) ON DELETE CASCADE
);

/*사진게시판*/
CREATE TABLE ALBUM (
    ANO INT UNSIGNED AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT NOT NULL,
    WRITER VARCHAR(10) NOT NULL,
    LOCATION VARCHAR(100),    
    STARTDATE DATE,
    ENDDATE DATE,
    REGDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    HIT INT UNSIGNED DEFAULT 0,
    REPLYCNT INT UNSIGNED DEFAULT 0,    
    BOARDTYPE VARCHAR(10) DEFAULT '2',        
    PRIMARY KEY (ANO),
    CONSTRAINT FK_USERS_ALBUM FOREIGN KEY (WRITER) REFERENCES USERS(USERID) ON DELETE CASCADE
);

/*사진게시판-첨부파일*/
CREATE TABLE ALBUM_ATTACH (
    UUID VARCHAR(100) NOT NULL,
    UPLOADPATH VARCHAR(200) NOT NULL,
    FILENAME VARCHAR(100) NOT NULL,    
    FILETYPE CHAR(1) DEFAULT 'I',
    ANO INT UNSIGNED,
    PRIMARY KEY (UUID),
    CONSTRAINT FK_ALBUM_ATTACH FOREIGN KEY (ANO) REFERENCES ALBUM(ANO) ON DELETE CASCADE
);

/*사진게시판-댓글*/
CREATE TABLE ALBUM_REPLY (
    RNO INT UNSIGNED AUTO_INCREMENT,    
    REPLY TEXT NOT NULL,
    REPLYER VARCHAR(50) NOT NULL,
    REPLYDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ANO INT UNSIGNED NOT NULL,
    BOARDTYPE VARCHAR(10) DEFAULT '2.1',    
    PRIMARY KEY (RNO),
    CONSTRAINT FK_ALBUM_REPLY FOREIGN KEY (ANO) REFERENCES ALBUM(ANO) ON DELETE CASCADE,
    CONSTRAINT FK_USERS_ALBUM_REPLY FOREIGN KEY (REPLYER) REFERENCES USERS(USERID) ON DELETE CASCADE
);

/*메인,소개화면*/
CREATE TABLE INTRO (
    BOARDTYPE TINYINT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    TSCRIPT TEXT,
    MAP VARCHAR(100),
    MSCRIPT TEXT,
    CAPTION VARCHAR(100),
    ADDRESS VARCHAR(100),
    ADDRESSDETAIL VARCHAR(100),
    INTRO TEXT,
    REGDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (BOARDTYPE)
);

/*메인,소개화면 - 첨부파일*/
CREATE TABLE INTRO_ATTACH (    
    UUID VARCHAR(100) NOT NULL,
    UPLOADPATH VARCHAR(200) NOT NULL,
    FILENAME VARCHAR(100) NOT NULL,
    FILETYPE CHAR(1) DEFAULT 'I',
    BOARDTYPE TINYINT NOT NULL,
    PRIMARY KEY (UUID),
    CONSTRAINT FK_INTRO_ATTACH FOREIGN KEY (BOARDTYPE) REFERENCES INTRO(BOARDTYPE)
);
